-- Run these statements as ACCOUNTADMIN in a Snowflake worksheet
-- Step 1: Create a dedicated warehouse, database, schema, and read-only role

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS CHAT_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND   = 60          -- suspend after 60 s idle (saves credits)
    AUTO_RESUME    = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS INSURANCE_DB;
CREATE SCHEMA   IF NOT EXISTS INSURANCE_DB.CLAIMS;

-- Read-only role for the app
CREATE ROLE IF NOT EXISTS CHAT_WH_ROLE;
GRANT USAGE  ON WAREHOUSE CHAT_WH               TO ROLE CHAT_WH_ROLE;
GRANT USAGE  ON DATABASE  INSURANCE_DB           TO ROLE CHAT_WH_ROLE;
GRANT USAGE  ON SCHEMA    INSURANCE_DB.CLAIMS    TO ROLE CHAT_WH_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA INSURANCE_DB.CLAIMS TO ROLE CHAT_WH_ROLE;
-- Keep this grant so future tables are auto-covered
ALTER DEFAULT PRIVILEGES IN SCHEMA INSURANCE_DB.CLAIMS
    GRANT SELECT ON TABLES TO ROLE CHAT_WH_ROLE;

-- Dedicated user
CREATE USER IF NOT EXISTS CHAT_WH_USER
    PASSWORD          = 'ChangeMe123!'   -- change before you use this
    DEFAULT_ROLE      = CHAT_WH_ROLE
    DEFAULT_WAREHOUSE = CHAT_WH
    DEFAULT_NAMESPACE = INSURANCE_DB.CLAIMS
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE CHAT_WH_ROLE TO USER CHAT_WH_USER;
